### ISSUE TITLE
Error in npm start

### ISSUE THREAD

**Issue by col-panic** [rgwch/webelexis#3]
Running npm start according to your guide leaves me with the folllowing error. Is that a configuration issue? Is mongodb required to run at this point? Did I miss something in your tutorial? Thanks!

```
Deployed successfully: emr 
Downloading io.vertx~mod-mongo-persistor~2.1.0. Please wait... 
Downloading 3%Downloading io.vertx~mod-mysql-postgresql_2.10~0.3.1. Please wait... 
Downloading 1%Exception in Java verticle 
java.lang.IllegalStateException: Client is closed
	at org.vertx.java.core.http.impl.DefaultHttpClient.checkClosed(DefaultHttpClient.java:781)
	at org.vertx.java.core.http.impl.DefaultHttpClient.get(DefaultHttpClient.java:243)
	at org.vertx.java.platform.impl.resolver.HttpResolution.sendRequest(HttpResolution.java:136)
	at org.vertx.java.platform.impl.resolver.HttpResolution.makeRequest(HttpResolution.java:159)
	at org.vertx.java.platform.impl.resolver.MavenResolution$6.handle(MavenResolution.java:115)
	at org.vertx.java.platform.impl.resolver.MavenResolution$6.handle(MavenResolution.java:109)
	at org.vertx.java.platform.impl.resolver.HttpResolution$2.handle(HttpResolution.java:163)
	at org.vertx.java.platform.impl.resolver.HttpResolution$2.handle(HttpResolution.java:159)
	at org.vertx.java.core.http.impl.DefaultHttpClientRequest.handleResponse(DefaultHttpClientRequest.java:287)
	at org.vertx.java.core.http.impl.ClientConnection.handleResponse(ClientConnection.java:332)
	at org.vertx.java.core.http.impl.DefaultHttpClient$ClientHandler.doMessageReceived(DefaultHttpClient.java:856)
	at org.vertx.java.core.http.impl.DefaultHttpClient$ClientHandler.doMessageReceived(DefaultHttpClient.java:836)
	at org.vertx.java.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:72)
	at org.vertx.java.core.net.impl.VertxHandler.channelRead(VertxHandler.java:155)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
``

**Comment by rgwch** [comment]
Hm, not sure. Probably you had bad luck with some of the dependencies that must be loaded on first launch. Try to install them separately:

vertx runmod io.vertx~mod-mysql-postgresql_2.10~0.3.1

Does this work?

And did the mod pull scala 2.10 on launch?

Mongodb is not required for first launch, you’ll get an error message in the web view if it’s not running when webelexis tries to log you in.

try 

npm run test-client

does this work? If so, try

npm run test-all

Hope that helps...

**Comment by col-panic** [comment]
okay,
```
vertx runmod io.vertx~mod-mysql-postgresql_2.10~0.3.1 
```
worked, after the next npm start he complained about mongo-persistory so i executed
```
vertx runmod io.vertx~mod-mongo-persistor~2.1.0
```

now it leaves me with

```
EMR Server started. got config {
  "icpc-problems" : true,
  "stickynotes" : true,
  "stickers" : true,
  "prescriptions" : true,
  "lab" : true,
  "role" : "arzt"
} 
Failed to create context 
java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:645)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:55)
	at java.security.KeyStore.load(KeyStore.java:1433)
	at org.vertx.java.core.net.impl.TCPSSLHelper.loadStore(TCPSSLHelper.java:366)
	at org.vertx.java.core.net.impl.TCPSSLHelper.getKeyMgrs(TCPSSLHelper.java:355)
	at org.vertx.java.core.net.impl.TCPSSLHelper.createContext(TCPSSLHelper.java:311)
	at org.vertx.java.core.net.impl.TCPSSLHelper.checkSSL(TCPSSLHelper.java:86)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:189)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:154)
	at ch.webelexis.CoreVerticle.start(CoreVerticle.java:152)
	at org.vertx.java.platform.impl.DefaultPlatformManager$21.run(DefaultPlatformManager.java:1758)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

Deployed successfully: account 
Deployed successfully: agenda 
Deployed successfully: emr 
Deployed successfully: mongo 
Exception in Java verticle 
java.lang.IllegalStateException: Client is closed
	at org.vertx.java.core.http.impl.DefaultHttpClient.checkClosed(DefaultHttpClient.java:781)
	at org.vertx.java.core.http.impl.DefaultHttpClient.get(DefaultHttpClient.java:243)
	at org.vertx.java.platform.impl.resolver.HttpResolution.sendRequest(HttpResolution.java:136)
	at org.vertx.java.platform.impl.resolver.HttpResolution.makeRequest(HttpResolution.java:159)
	at org.vertx.java.platform.impl.resolver.MavenResolution$6.handle(MavenResolution.java:115)
	at org.vertx.java.platform.impl.resolver.MavenResolution$6.handle(MavenResolution.java:109)
	at org.vertx.java.platform.impl.resolver.HttpResolution$2.handle(HttpResolution.java:163)
	at org.vertx.java.platform.impl.resolver.HttpResolution$2.handle(HttpResolution.java:159)
	at org.vertx.java.core.http.impl.DefaultHttpClientRequest.handleResponse(DefaultHttpClientRequest.java:287)
	at org.vertx.java.core.http.impl.ClientConnection.handleResponse(ClientConnection.java:332)
	at org.vertx.java.core.http.impl.DefaultHttpClient$ClientHandler.doMessageReceived(DefaultHttpClient.java:856)
	at org.vertx.java.core.http.impl.DefaultHttpClient$ClientHandler.doMessageReceived(DefaultHttpClient.java:836)
	at org.vertx.java.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:72)
	at org.vertx.java.core.net.impl.VertxHandler.channelRead(VertxHandler.java:155)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

Starting async database module for MySQL and PostgreSQL. 
could not start async database module! 
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at org.vertx.java.core.json.JsonObject.getInteger(JsonObject.java:220)
	at io.vertx.asyncsql.Starter.getConfiguration(Starter.scala:60)
	at io.vertx.asyncsql.Starter.start(Starter.scala:26)
	at org.vertx.scala.platform.impl.ScalaVerticle.start(ScalaVerticle.scala:65)
	at org.vertx.java.platform.impl.DefaultPlatformManager$21.run(DefaultPlatformManager.java:1758)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

failed to deploy sql: null 
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at org.vertx.java.core.json.JsonObject.getInteger(JsonObject.java:220)
	at io.vertx.asyncsql.Starter.getConfiguration(Starter.scala:60)
	at io.vertx.asyncsql.Starter.start(Starter.scala:26)
	at org.vertx.scala.platform.impl.ScalaVerticle.start(ScalaVerticle.scala:65)
	at org.vertx.java.platform.impl.DefaultPlatformManager$21.run(DefaultPlatformManager.java:1758)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
```

I did a git pull to update just before :)

**Comment by col-panic** [comment]
```
npm run test-client 
```
exits with

```
/home/webelexis/webelexis/webelexis-base/node_modules/karma/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
            ^
Error: No provider for "framework:chai-sinon"! (Resolving: framework:chai-sinon)
    at error (/home/webelexis/webelexis/webelexis-base/node_modules/karma/node_modules/di/lib/injector.js:22:68)
    at Object.parent.get (/home/webelexis/webelexis/webelexis-base/node_modules/karma/node_modules/di/lib/injector.js:9:13)
    at get (/home/webelexis/webelexis/webelexis-base/node_modules/karma/node_modules/di/lib/injector.js:54:19)
    at /home/webelexis/webelexis/webelexis-base/node_modules/karma/lib/server.js:31:14
    at Array.forEach (native)
    at start (/home/webelexis/webelexis/webelexis-base/node_modules/karma/lib/server.js:30:21)
    at invoke (/home/webelexis/webelexis/webelexis-base/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Object.exports.start (/home/webelexis/webelexis/webelexis-base/node_modules/karma/lib/server.js:314:12)
    at Object.exports.run (/home/webelexis/webelexis/webelexis-base/node_modules/karma/lib/cli.js:229:25)
    at requireCliAndRun (/usr/lib/node_modules/karma-cli/bin/karma:24:16)

npm ERR! base-module@0.4.1 test-client: `npm run clean && npm run build-client && karma start karma_cfg.js --single-run`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the base-module@0.4.1 test-client script.
npm ERR! This is most likely a problem with the base-module package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run build-client && karma start karma_cfg.js --single-run
npm ERR! You can get their info via:
npm ERR!     npm owner ls base-module
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-46-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "run" "test-client"
npm ERR! cwd /home/webelexis/webelexis/webelexis-base
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/webelexis/webelexis/webelexis-base/npm-debug.log
npm ERR! not ok code 0
``

**Comment by rgwch** [comment]
Oh, that’s an improvement :)

I’m afraid, I changed some stuff too fast and too frequent the last days… Still learning… But things should stabilize now.

1) go to the webelexis-base directory and type: 'npm install' (should fix the „no provider for…“ error)
2) create a new webelexis-base/cfglocal.json based on the current src/main/resources/config_sample.json.  (mysql port should be a number, not a String. And some other changes)
3) Tell me, which errors persist :)

(or meet me in Schaffhausen or Lenzburg next week :))

**Comment by col-panic** [comment]
Thanks a lot! I was left with the original problem again
```
 java.lang.IllegalStateException: Client is closed
```
but after configuring ```ssl:false``` in cfgLocal npm start worked out :)

Accessing the website unfortunately leaves me with an empty screen with html source code

```
<!-- This file is part of Webelexis, copyright (c) 2015 by G. Weirich--><!DOCTYPE html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="clientID" content="3aa2352634636aasf.apps.googleusercontent.com"><meta name="state" content="91c429c1-1583-4c16-b236-aa00033a74cb"><meta name="UUID" content="271ae26e-fc1a-44d2-87e1-198b3b0b7049"><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"><link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css"><link rel="stylesheet" href="css/style.css"><title data-bind="text: router.currentPage().title">Webelexis</title><script src="app/requirejs.config.js"></script><script src="https://apis.google.com/js/platform.js" async defer></script><script data-main="app/main.js" src="lib/require.js"></script></head><body><noscript>Sie können diese Seite nur mit einem JavaScript-fähigen Browser benutzen.</noscript><div class="container"><div id="menu" data-bind="component: {name: 'ch-webelexis-menubar', params: {menu: 'mainMenu'}}"></div><div id="content" data-bind="component: { 'name': router.currentPage().componentName, 'params': {params: router.currentPage().params}}">         </div></div></body></html>
```

**Comment by rgwch** [comment]
(o.o)(-.-)(O.O) ???

Weird.

This is the answer from http://localhost:2015 ???

Which browser is it? Is Javascript enabled?

If not Chrome, try it with Chrome, plz.

I know, that Opera doesn’t work, but Chrome, Safari and Firefox do work here in Mac and Linux versions.
Is there an error message in the console? (F12 on Linux, alt-cmd-I on mac)

Quite challenging. Fortunately there are not so many users up to now :)

**Comment by rgwch** [comment]
Sorry!
This was an error in yesterday’s commit

git pull again, restart and it should work

**Comment by col-panic** [comment]
No I started it on a server in the network. All the links within the 
HTML do work If I click on them. Yet both Firefox and Chrome do only 
show an empty page.

The server does not show anything special

```
Deployed successfully: emr
Deployed successfully: mongo
Starting async database module for MySQL and PostgreSQL.
Async database module for MySQL and PostgreSQL started with config 
Configuration(elexisuser,localhost,3306,Some(elexisuser),Some(elexis),UTF-8,16777216,PooledByteBufAllocator(directByDefault: 
true),5 seconds,5 seconds)
Deployed successfully: sql
Downloading rgwch~vertx-mod-sessionmgr~0.5.2. Please wait...
Downloading 100%
Module rgwch~vertx-mod-sessionmgr~0.5.2 successfully installed
Deployed successfully: auth
Succeeded in deploying verticle
Thu May 07 14:51:10 CEST 2015 - Created session: 
66b77480-b779-4b2f-b04c-1a83df5bc38a
Thu May 07 14:51:48 CEST 2015 - Created session: 
4b66162c-055b-40a1-99de-34159d5ac247
Thu May 07 14:51:50 CEST 2015 - Created session: 
271ae26e-fc1a-44d2-87e1-198b3b0b7049
Thu May 07 14:53:50 CEST 2015 - Created session: 
22f67aab-2118-4b0c-a0cf-5cf65f40aabc
Thu May 07 15:03:00 CEST 2015 - Created session: 
d63e857a-5238-412b-838d-cb4e08073543
Thu May 07 15:03:13 CEST 2015 - Created session: 
2a5b09bb-dc13-47c3-af50-b84c72b206c6
Thu May 07 15:03:16 CEST 2015 - Created session: 
43600903-38af-483f-bfba-64ed2e091482
Thu May 07 15:04:18 CEST 2015 - Created session: 
fd245986-54e1-44a2-a7b7-1763b057b4b0
Thu May 07 15:04:21 CEST 2015 - Created session: 
815d9c99-5ec0-4dc2-8fb1-57c162d9344d
Thu May 07 15:04:30 CEST 2015 - Created session: 
f3530d97-3693-45f5-88f8-87ca824b41dd
Thu May 07 15:04:31 CEST 2015 - Created session: 
393dbd5e-3e67-4977-9b6d-6078d6ba3260
Thu May 07 15:04:33 CEST 2015 - Created session: 
63d32ba6-a8d5-433a-91ff-5d7df4e59af5
Thu May 07 15:04:58 CEST 2015 - Created session: 
6d585148-9c77-41a7-bbb2-0c264d29029a
Thu May 07 15:05:01 CEST 2015 - Created session: 
05280d40-3828-4e05-9807-993a31440500
```

Console says

```
Error: Script error for: bus
http://requirejs.org/docs/errors.html#scripterror


var e = new Error(msg + '\nhttp://requirejs.org/docs/errors.html#' + id);
-----------|
```

:)

rgwch schrieb:

**Comment by col-panic** [comment]
And the winner is ..... got it working :+1: 
thanks a lot!!
